name: tripeaks_neue
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  audioplayers: ^6.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.3.0
  intl: any
  logger: ^2.5.0
  mobx: ^2.5.0
  path_provider: ^2.1.5
  provider: ^6.1.2

  # cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  mobx_codegen: ^2.7.0

flutter:
  uses-material-design: true
  # generate: true

  assets:
    - images/tropy.png
    - images/empty.png
    - sounds/138410__cameronmusic__item-collect-2.mp3
    - sounds/608431__plasterbrain__shiny-coin-pickup.mp3
    - sounds/138490__justinvoke__powerdown-2.mp3
    - sounds/608433__plasterbrain__nintendo-coin-pickup.mp3
    - sounds/423169__plasterbrain__pc-game-ui-error.mp3
    - sounds/656394__nikos34__select-2.mp3
    - sounds/50559__broumbroum__sf3-sfx-menu-select-l.mp3

  fonts:
    - family: Peaks-Neue
      fonts:
        - asset: fonts/Peaks-Neue.ttf
    - family: Outfit
      fonts:
        - asset: fonts/Outfit-VariableFont_wght.ttf