name: tripeaks_neue
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.3.0
  intl: any
  mobx: ^2.5.0
  provider: ^6.1.2

  # cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  mobx_codegen: ^2.7.0

flutter:
  uses-material-design: true
  # generate: true

  assets:
    - images/title.png

  fonts:
    - family: Peaks-Neue
      fonts:
        - asset: fonts/Peaks-Neue.ttf
    - family: Outfit
      fonts:
        - asset: fonts/Outfit-VariableFont_wght.ttf