name: Release AppImage

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa clang \
          cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev \
          libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev squashfs-tools

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build linux bundle
        run: flutter build linux --release

      - uses: AppImageCrafters/build-appimage@master
        with:
          recipe: "./AppImageBuilder.yml"

      - name: Upload AppImage
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./
          asset_name: tripeaks_neue.AppImage
          asset_content_type: application/octet-stream